version: '3.8'

services:
  api:
    build: .
    command: uvicorn challenge.api:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/challenge
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
