name: Continuous Delivery

on:
  push:
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:
  workflow_run:
    workflows: [ "Continuous Integration" ]
    types:
      - completed


env:
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_EXPERIMENT_NAME: ${{ secrets.MLFLOW_EXPERIMENT_NAME }}

permissions:
  pages: write
  contents: write
  id-token: write

jobs:
  setup:
    name: Setup environment
    uses: ./.github/workflows/common.yml
    secrets: inherit

  staging:
    name: Staging
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Build Docker image
        run: |
          docker build -t skyprophet:latest .

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [staging, setup]
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Build Docker image
        run: |
          docker build -t skyprophet:latest .
